### ISSUE TITLE
all new images are considered "already Downloaded"

### ISSUE THREAD

**Issue by Butterfly-Dragon** [RipMeApp/ripme#1138]
* Ripme version:
1.7.75

* Java version: 
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

* Operating system: 
Microsoft Windows [Version 10.0.17763.195]

* Exact URL you were trying to rip when the problem occurred:
https://www.artstation.com/raikoart

* Please include any additional information about how to reproduce the problem:
With the "remember URL history" option ticked the ripper fails to download any new image

Detail the expected behavior here.

Being a new gallery never downloaded before i expected it to download the gallery

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

every image has been flagged as "already downloaded" and was thus not downloaded. Their urls have been added to the url_history log to not be downloaded anymore.

**Comment by cyian-1756** [comment]
This is ripme working as intended. If the urls are in url_history.txt then they will not be redownloaded. To disable this feature uncheck "Remember URL History" in the gui

**Comment by Butterfly-Dragon** [comment]
Exactly: the pictures had never been downloaded before. But they are considered as if downloaded.

**Comment by cyian-1756** [comment]
This was fixed in update 1.7.76

**Comment by samerickson** [comment]
I am still getting the error while using: https://www.reddit.com/r/unixporn/ to test.

**Comment by cyian-1756** [comment]
> I am still getting the error while using: https://www.reddit.com/r/unixporn/ to test.

I can't reproduce that. All the urls from that sub are probably already in your url_history

**Comment by Butterfly-Dragon** [comment]
on that note: a nice feature would be a line of "comment" in the downloaded urls log telling us when a downloading session has started and its time/date so that if we want to remove some urls (like in this case) we know how far to go back.
