### ISSUE TITLE
imgbox ripper is broken

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#114]
* Ripme version: 1.5.15
* Java version: 1.8.0_131
* Operating system: Ubuntu 16.04
* Exact URL you were trying to rip when the problem occurred: https://imgbox.com/g/FJPF7t26FD
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The ripper should download all the images

## Actual Behavior

The ripper 404s on all the images

**Comment by nzbtuxnews** [comment]
Same here, and same behavior with FF's plugin "Imagehost grabber".  SO far I'm leaning towards Imgbox secured their stuff to prevent scraping because accessing the pics one by one (normally) works.

**Comment by nzbtuxnews** [comment]
Still doesnt work with 1.6.2  most galleries are 404 on all images

"Non-retriable status code 404 "
Try with this one https://imgbox.com/g/jiAIZVYLWw

**Comment by rautamiekka** [comment]
^ Yeah and I found the culprit: you don't have everything on `thumbs` and `images` subdomains, but there are numbered subdomains like `thumbs2` and `images2` like in the case of that album, so it's RegEx time again:

Detecting the thumbs in HTML code _(I recognize the RegEx might need improving)_:
```
"https?://thumbs([0-9]*)\.imgbox\.com/[a-z0-9/]+?/[^"\.]{8}_b\.[^"]+"
```

From the whole match replace `thumbs` and `_b` like before. All done.

SFW functional examples the RegEx worked on:
- thumb: https://thumbs2.imgbox.com/c3/df/dlzKHNuk_b.jpeg
- full: https://images2.imgbox.com/c3/df/dlzKHNuk_o.jpeg

**Comment by cyian-1756** [comment]
@rautamiekka Couldn't I just change the replace on line 51 to change out "thumbs" with "images" and avoid having to use a regex?

**Comment by rautamiekka** [comment]
^ How will you match the link if the thumbnail subdomain contains numbers, or Heaven forbid, something else in addition to 'thumbs' ? Otherwise it's a sound idea.

**Comment by cyian-1756** [comment]
> How will you match the link if the thumbnail subdomain contains numbers

Using jsoup. The thumbnails are all still at the same spot css wise

> Heaven forbid, something else in addition to 'thumbs' 

That'll mess it right up, but I can't find any albums that use anything besides thumbs[1-9]

**Comment by cyian-1756** [comment]
Fixed in PR #133. I merge it and make a new release later

**Comment by nzbtuxnews** [comment]
Still broken I fear.  Galleries are downloading thumbnails and not the full size pics.

Try with this one: https://imgbox.com/g/ePw8A1LMGd
