### ISSUE TITLE
RipMe doesn't download all images and videos uploaded by a Twitter user.

### ISSUE THREAD

**Issue by tarantinosaur** [RipMeApp/ripme#708]
* Ripme version:
* Java version: 1.7.52
* Operating system: Windows version 6.3.9600
* https://twitter.com/DevirginizerTop/ **(Warning: gay porn)**
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

RipMe downloads all 96 pictures and videos of the linked user.

## Actual Behavior

RipMe only downloaded 66 of them.

**Comment by tarantinosaur** [comment]
I don't know if this can help but you could try looking at [this extension](https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig?hl=en) in Chrome which can download all media of a user successfully. It's what I'm using as of the moment.

**Comment by cyian-1756** [comment]
This is because the twitter ripper doesn't rip retweets, this has been fixed in #705 and will be in ripme 1.7.53

**Comment by tarantinosaur** [comment]
I don't intend to download the retweets, only the ones uploaded by the user.

**Comment by cyian-1756** [comment]
This should be fixed in 1.7.57 @tarantinosaur can you test and confirm?

**Comment by tarantinosaur** [comment]
It's still downloading the retweets, and it still can't download every photos and videos of a user.
